accounts/urls.py
from . import views
from django.urls import path


app_name = "accounts"

urlpatterns = [
    path(
        '',
        views.LoginView.as_view(),
        name='login'
    ),
    path(
        'accounts/register/',
        views.RegisterView.as_view(),
        name='register'
    ),
    path(
        'accounts/logout/',
        views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        'accounts/password-reset/',
        views.PasswordResetCustomView.as_view(),
        name="password_reset"
    ),
    path(
        'accounts/password-reset-confirm/<uidb64>/<token>',
        views.PasswordResetConfirmCustomView.as_view(
            template_name='accounts/password_reset_confirm.html'
        ),
        name="password_reset_confirm"
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

dashboard/urls.py
from . import views
from leads import views as leads_views
from accounts import views as accounts_views
from django.urls import path

app_name = "dashboard"

urlpatterns = [
    path(
        '',
        views.DashboardView.as_view(),
        name='home'
    ),
    path(
        'profile/',
        accounts_views.UserProfileView.as_view(),
        name='profile'
    ),
    path(
        'leads/',
        leads_views.LeadView.as_view(),
        name='leads'
    ),
    path(
        'leads/search/',
        leads_views.LeadSearchView.as_view(),
        name='leads_search'
    ),
    path(
        'leads/export/',
        leads_views.LeadExportView.as_view(),
        name='leads_export'
    ),
    path(
        'leads/<int:pk>/update/',
        leads_views.LeadUpdateView.as_view(),
        name='leads_update'
    ),
    path(
        'leads/<int:pk>/delete/',
        leads_views.LeadDeleteView.as_view(),
        name='leads_delete'
    ),
    path(
        'leads/category/',
        leads_views.CategoryView.as_view(),
        name='leads_category'
    ),
    path(
        'leads/category/search/',
        leads_views.CategorySearchView.as_view(),
        name='leads_category_search'
    ),
    path(
        'leads/category/export/',
        leads_views.CategoryExportView.as_view(),
        name='leads_category_export'
    ),
    path(
        'leads/category/<int:pk>/update/',
        leads_views.CategoryUpdateView.as_view(),
        name='leads_category_update'
    ),
    path(
        'leads/category/<int:pk>/delete/',
        leads_views.CategoryDeleteView.as_view(),
        name='leads_category_delete'
    ),
    path(
        'leads/agent/',
        leads_views.AgentView.as_view(),
        name='leads_agent'
    ),
    path(
        'leads/agent/export/',
        leads_views.AgentExportView.as_view(),
        name='leads_agent_export'
    ),
    path(
        'leads/agent/search/',
        leads_views.AgentSearchView.as_view(),
        name='leads_agent_search'
    ),
    path(
        'leads/agent/<int:pk>/update/',
        leads_views.AgentUpdateView.as_view(),
        name='leads_agent_update'
    ),
    path(
        'leads/agent/<int:pk>/delete/',
        leads_views.AgentDeleteView.as_view(),
        name='leads_agent_delete'
    ),
]

users/urls.py
from . import views
from django.urls import path


app_name = "users"

urlpatterns = [
    path(
        '',
        views.LoginView.as_view(),
        name='login'
    ),
    path(
        'users/register/',
        views.RegisterView.as_view(),
        name='register'
    ),
    path(
        'users/logout/',
        views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        'users/password-reset/',
        views.PasswordResetCustomView.as_view(),
        name="password_reset"
    ),
    path(
        'users/password-reset-confirm/<uidb64>/<token>',
        views.PasswordResetConfirmCustomView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name="password_reset_confirm"
    ),
]

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic


class DashboardView(LoginRequiredMixin, generic.View):
    login_url = "accounts:login"
    template_name = 'dashboard/pages/dashboard_home.html'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def setup(self, *args, **kwargs):
        return super().setup(*args, **kwargs)

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request):
        return render(request, self.template_name)

templates/dashboard/partials/my_profile.html
<section class="bg-gray-50 dark:bg-gray-900 p-3 sm:p-5">
    <div class="bg-gray-100 dark:bg-gray-800 px-5 py-10 mx-auto max-w-screen-xl lg:px-5 elative shadow rounded-lg w-6/6 md:w-5/6 lg:w-4/6 xl:w-3/6">
        <div class="flex justify-center items-center mb-10">
            {% if user.avatar %}
            {% else %}
                <img src="https://www.svgrepo.com/download/5125/avatar.svg"
                     class="w-32 rounded-full"
                     alt="Avatar" />
            {% endif %}
        </div>
        <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Profile Information</h2>
        <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
            <div class="sm:col-span-2">
                <label for="first_name"
                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">First Name</label>
                <input type="text"
                       name="first_name"
                       id="first_name"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                       {% if user.first_name %} placeholder="{{ user.first_name }}" {% else %} placeholder="No registered first name" {% endif %}
                       disabled>
            </div>
            <div class="sm:col-span-2">
                <label for="last_name"
                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Last Name</label>
                <input type="text"
                       name="last_name"
                       id="last_name"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                       {% if user.last_name %} placeholder="{{ user.last_name }}" {% else %} placeholder="No registered last name" {% endif %}
                       disabled>
            </div>
            <div class="sm:col-span-2">
                <label for="username"
                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Username</label>
                <input type="text"
                       name="username"
                       id="username"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                       {% if user.username %} placeholder="{{ user.username }}" {% else %} placeholder="No registered username" {% endif %}
                       disabled>
            </div>
            <div class="sm:col-span-2">
                <label for="email"
                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Email</label>
                <input type="text"
                       name="email"
                       id="email"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                       {% if user.email %} placeholder="{{ user.email }}" {% else %} placeholder="No registered email" {% endif %}
                       disabled>
            </div>
        </div>
    </div>
</section>

templates/dashboard/partials/navbar.html
{% load static %}
<nav class="bg-white border-b border-gray-200 px-4 py-2.5 dark:bg-gray-800 dark:border-gray-700 fixed left-0 right-0 top-0 z-50">
    <div class="flex flex-wrap justify-between items-center">
        <div class="flex justify-start items-center">
            <button data-drawer-target="drawer-navigation"
                    data-drawer-toggle="drawer-navigation"
                    aria-controls="drawer-navigation"
                    class="p-2 mr-2 text-gray-600 rounded-lg cursor-pointer md:hidden hover:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 dark:focus:bg-gray-700 focus:ring-2 focus:ring-gray-100 dark:focus:ring-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                <svg aria-hidden="true"
                     class="w-6 h-6"
                     fill="currentColor"
                     viewBox="0 0 20 20"
                     xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd">
                    </path>
                </svg>
                <svg aria-hidden="true"
                     class="hidden w-6 h-6"
                     fill="currentColor"
                     viewBox="0 0 20 20"
                     xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd">
                    </path>
                </svg>
                <span class="sr-only">Toggle sidebar</span>
            </button>
            <a href="https://github.com/Peagah-Vieira/Django-CRM"
               class="flex items-center justify-between mr-4">
                <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Django-CRM</span>
            </a>
        </div>
        <div class="flex items-center lg:order-2">
            <!-- Apps -->
            <button type="button"
                    data-dropdown-toggle="apps-dropdown"
                    class="p-2 text-gray-500 rounded-lg hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-700 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600">
                <i class="fa-brands fa-figma fa-xl"></i>
            </button>
            <!-- Dropdown menu -->
            <div class="hidden overflow-hidden z-50 my-4 max-w-sm text-base list-none bg-white rounded divide-y divide-gray-100 shadow-lg dark:bg-gray-700 dark:divide-gray-600"
                 id="apps-dropdown">
                <div class="block py-2 px-4 text-base font-medium text-center text-gray-700 bg-gray-50 dark:bg-gray-600 dark:text-gray-300">
                    Apps
                </div>
                <div class="grid grid-cols-3 gap-4 p-4">
                    <a href="{% url 'dashboard:leads' %}"
                       class="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group">
                        <i class="fa-solid fa-pencil fa-xl mx-auto mb-1 first-line:text-gray-400 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"
                           aria-hidden="true">
                        </i>
                        <div class="text-sm pt-2 text-gray-900 dark:text-white">Leads</div>
                    </a>
                    <a href="{% url 'dashboard:leads_category' %}"
                       class="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group">
                        <i class="fa-solid fa-folder fa-xl mx-auto mb-1 first-line:text-gray-400 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"
                           aria-hidden="true">
                        </i>
                        <div class="text-sm pt-2 text-gray-900 dark:text-white">Categories</div>
                    </a>
                    <a href="{% url 'dashboard:leads_agent' %}"
                       class="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group">
                        <i class="fa-solid fa-user-tie fa-xl mx-auto mb-1 first-line:text-gray-400 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"
                           aria-hidden="true">
                        </i>
                        <div class="text-sm pt-2 text-gray-900 dark:text-white">Agents</div>
                    </a>
                    <a href="{% url 'dashboard:profile' %}"
                       class="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group">
                        <i class="fa-solid fa-user fa-xl mx-auto mb-1 first-line:text-gray-400 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"
                           aria-hidden="true">
                        </i>
                        <div class="text-sm pt-2 text-gray-900 dark:text-white">Profile</div>
                    </a>
                    <button id="theme-toggle"
                            type="button"
                            class="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group">
                        <i id="theme-toggle-dark-icon"
                           class="fa-solid fa-moon fa-xl hidden mx-auto mb-1 first-line:text-gray-400 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"></i>
                        <i id="theme-toggle-light-icon"
                           class="fa-solid fa-sun fa-xl hidden mx-auto mb-1 first-line:text-gray-400 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"></i>
                        <div class="text-sm pt-2 text-gray-900 dark:text-white">Theme</div>
                    </button>
                    <form action="{% url 'accounts:logout' %}" method="POST">
                        {% csrf_token %}
                        <button type="submit"
                                class="text-sm block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group">
                            <i class="fa-solid fa-right-from-bracket fa-rotate-180 fa-xl mx-auto mb-1 first-line:text-gray-400 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"
                               aria-hidden="true">
                            </i>
                            <div class="text-sm pt-3 text-gray-900 dark:text-white">Logout</div>
                        </button>
                    </form>
                </div>
            </div>
            <button type="button"
                    class="flex mx-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
                    id="user-menu-button"
                    aria-expanded="false"
                    data-dropdown-toggle="dropdown">
                <span class="sr-only">Open user menu</span>
                <img class="w-8 h-8 rounded-full"
                     src="https://www.svgrepo.com/download/5125/avatar.svg"
                     alt="avatar" />
            </button>
            <!-- Dropdown menu -->
            <div class="hidden z-50 my-4 w-56 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600"
                 id="dropdown">
                <div class="py-3 px-4">
                    <span class="block text-sm font-semibold text-gray-900 dark:text-white">{{ user.username }}</span>
                </div>
                <ul class="py-1 text-gray-700 dark:text-gray-300"
                    aria-labelledby="dropdown">
                    <li>
                        <a href="{% url 'dashboard:profile' %}"
                           class="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">My profile</a>
                    </li>
                </ul>
                <ul class="py-1 text-gray-700 dark:text-gray-300"
                    aria-labelledby="dropdown">
                    <li>
                        <form action="{% url 'accounts:logout' %}" method="POST">
                            {% csrf_token %}
                            <button type="submit"
                                    class="block w-full text-start py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                                Sign out
                            </button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
<!-- Theme Switcher JS -->
<script>
var themeToggleDarkIcon = document.getElementById('theme-toggle-dark-icon');
var themeToggleLightIcon = document.getElementById('theme-toggle-light-icon');

// Change the icons inside the button based on previous settings
if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
    themeToggleLightIcon.classList.remove('hidden');
} else {
    themeToggleDarkIcon.classList.remove('hidden');
}

var themeToggleBtn = document.getElementById('theme-toggle');

themeToggleBtn.addEventListener('click', function () {

    // toggle icons inside button
    themeToggleDarkIcon.classList.toggle('hidden');
    themeToggleLightIcon.classList.toggle('hidden');

    // if set via local storage previously
    if (localStorage.getItem('color-theme')) {
        if (localStorage.getItem('color-theme') === 'light') {
            document.documentElement.classList.add('dark');
            localStorage.setItem('color-theme', 'dark');
        } else {
            document.documentElement.classList.remove('dark');
            localStorage.setItem('color-theme', 'light');
        }

        // if NOT set via local storage previously
    } else {
        if (document.documentElement.classList.contains('dark')) {
            document.documentElement.classList.remove('dark');
            localStorage.setItem('color-theme', 'light');
        } else {
            document.documentElement.classList.add('dark');
            localStorage.setItem('color-theme', 'dark');
        }
    }

});
</script>

templates/dashboard/partials/sidebar.html
<aside class="fixed top-0 left-0 z-40 w-64 h-screen pt-14 transition-transform -translate-x-full bg-white border-r border-gray-200 md:translate-x-0 dark:bg-gray-800 dark:border-gray-700"
       aria-label="Sidenav"
       id="drawer-navigation">
    <div class="overflow-y-auto py-5 px-3 h-full bg-white dark:bg-gray-800">
        <ul class="space-y-2">
            <!-- Home -->
            <li>
                <a href="{% url 'dashboard:home' %}"
                   class="flex items-center p-2 text-base font-medium text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <i class="fa-solid fa-house fa-lg text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
                       aria-hidden="true">
                    </i>
                    <span class="ml-3">Home</span>
                </a>
            </li>
            <!-- Leads -->
            <li>
                <a href="{% url 'dashboard:leads' %}"
                   class="flex items-center p-2 text-base font-medium text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <i class="fa-solid fa-pencil fa-lg text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
                       aria-hidden="true">
                    </i>
                    <span class="ml-3">Leads</span>
                </a>
            </li>
            <!-- Categories -->
            <li>
                <a href="{% url 'dashboard:leads_category' %}"
                   class="flex items-center p-2 text-base font-medium text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <i class="fa-solid fa-folder fa-lg text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
                       aria-hidden="true">
                    </i>
                    <span class="ml-3">Categories</span>
                </a>
            </li>
            <!-- Agents -->
            <li>
                <a href="{% url 'dashboard:leads_agent' %}"
                   class="flex items-center p-2 text-base font-medium text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <i class="fa-solid fa-user-tie fa-lg text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
                       aria-hidden="true">
                    </i>
                    <span class="ml-3">Agents</span>
                </a>
            </li>
        </ul>
        <ul class="pt-5 mt-5 space-y-2 border-t border-gray-200 dark:border-gray-700">
            <!-- Documentation -->
            <li>
                <button type="button"
                        class="flex items-center p-2 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700"
                        aria-controls="dropdown-leads"
                        data-collapse-toggle="dropdown-leads">
                    <i class="fa-solid fa-file fa-lg flex-shrink-0 text-gray-500 transition duration-75 group-hover:text-gray-900 dark:text-gray-400 dark:group-hover:text-white"
                       aria-hidden="true">
                    </i>
                    <span class="flex-1 ml-3 text-left whitespace-nowrap">Documentation</span>
                    <i class="fa-sharp fa-solid fa-arrow-down fa-sm"></i>
                </button>
                <ul id="dropdown-leads" class="hidden py-2 space-y-2">
                    <li>
                        <a href="https://flowbite.com/blocks/"
                           target="_blank"
                           class="flex items-center p-2 pl-11 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">Tailwind</a>
                    </li>
                    <li>
                        <a href="https://tailwindcss.com"
                           target="_blank"
                           class="flex items-center p-2 pl-11 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">Flowbite</a>
                    </li>
                    <li>
                        <a href="https://github.com/Peagah-Vieira/Django-CRM"
                           target="_blank"
                           class="flex items-center p-2 pl-11 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">Github Repository</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</aside>

templates/dashboard/partials/table_nav.html
<nav class="flex flex-col md:flex-row justify-between items-start md:items-center space-y-3 md:space-y-0 p-4"
     aria-label="Table navigation">
    <span class="text-sm font-normal text-gray-500 dark:text-gray-400">
        Showing
        <span class="font-semibold text-gray-900 dark:text-white">1-10</span>
        of
        <span class="font-semibold text-gray-900 dark:text-white">1000</span>
    </span>
    <ul class="inline-flex items-stretch -space-x-px">
        <li>
            <a href="#"
               class="flex items-center justify-center h-full py-1.5 px-3 ml-0 text-gray-500 bg-white rounded-l-lg border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                <span class="sr-only">Previous</span>
                <svg class="w-5 h-5"
                     aria-hidden="true"
                     fill="currentColor"
                     viewbox="0 0 20 20"
                     xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
                </svg>
            </a>
        </li>
        <li>
            <a href="#"
               class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">1</a>
        </li>
        <li>
            <a href="#"
               class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">2</a>
        </li>
        <li>
            <a href="#"
               aria-current="page"
               class="flex items-center justify-center text-sm z-10 py-2 px-3 leading-tight text-primary-600 bg-primary-50 border border-primary-300 hover:bg-primary-100 hover:text-primary-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white">3</a>
        </li>
        <li>
            <a href="#"
               class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">...</a>
        </li>
        <li>
            <a href="#"
               class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">100</a>
        </li>
        <li>
            <a href="#"
               class="flex items-center justify-center h-full py-1.5 px-3 leading-tight text-gray-500 bg-white rounded-r-lg border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                <span class="sr-only">Next</span>
                <svg class="w-5 h-5"
                     aria-hidden="true"
                     fill="currentColor"
                     viewbox="0 0 20 20"
                     xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                </svg>
            </a>
        </li>
    </ul>
</nav>