config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

dashboard/urls.py
from . import views
from leads import views as leads_views
from accounts import views as accounts_views
from django.urls import path

app_name = "dashboard"

urlpatterns = [
    path(
        '',
        views.DashboardView.as_view(),
        name='home'
    ),
    path(
        'profile/',
        accounts_views.UserProfileView.as_view(),
        name='profile'
    ),
    path(
        'leads/',
        leads_views.LeadView.as_view(),
        name='leads'
    ),
    path(
        'leads/search/',
        leads_views.LeadSearchView.as_view(),
        name='leads_search'
    ),
    path(
        'leads/export/',
        leads_views.LeadExportView.as_view(),
        name='leads_export'
    ),
    path(
        'leads/<int:pk>/update/',
        leads_views.LeadUpdateView.as_view(),
        name='leads_update'
    ),
    path(
        'leads/<int:pk>/delete/',
        leads_views.LeadDeleteView.as_view(),
        name='leads_delete'
    ),
    path(
        'leads/category/',
        leads_views.CategoryView.as_view(),
        name='leads_category'
    ),
    path(
        'leads/category/search/',
        leads_views.CategorySearchView.as_view(),
        name='leads_category_search'
    ),
    path(
        'leads/category/export/',
        leads_views.CategoryExportView.as_view(),
        name='leads_category_export'
    ),
    path(
        'leads/category/<int:pk>/update/',
        leads_views.CategoryUpdateView.as_view(),
        name='leads_category_update'
    ),
    path(
        'leads/category/<int:pk>/delete/',
        leads_views.CategoryDeleteView.as_view(),
        name='leads_category_delete'
    ),
    path(
        'leads/agent/',
        leads_views.AgentView.as_view(),
        name='leads_agent'
    ),
    path(
        'leads/agent/export/',
        leads_views.AgentExportView.as_view(),
        name='leads_agent_export'
    ),
    path(
        'leads/agent/search/',
        leads_views.AgentSearchView.as_view(),
        name='leads_agent_search'
    ),
    path(
        'leads/agent/<int:pk>/update/',
        leads_views.AgentUpdateView.as_view(),
        name='leads_agent_update'
    ),
    path(
        'leads/agent/<int:pk>/delete/',
        leads_views.AgentDeleteView.as_view(),
        name='leads_agent_delete'
    ),
]

users/urls.py
from . import views
from django.urls import path


app_name = "users"

urlpatterns = [
    path(
        '',
        views.LoginView.as_view(),
        name='login'
    ),
    path(
        'users/register/',
        views.RegisterView.as_view(),
        name='register'
    ),
    path(
        'users/logout/',
        views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        'users/password-reset/',
        views.PasswordResetCustomView.as_view(),
        name="password_reset"
    ),
    path(
        'users/password-reset-confirm/<uidb64>/<token>',
        views.PasswordResetConfirmCustomView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name="password_reset_confirm"
    ),
]

leads/forms/agent_create_form.py
from django import forms
from leads.models import Agent


class AgentForm(forms.ModelForm):
    class Meta:
        model = Agent
        fields = [
            "first_name",
            "last_name",
            "email",
            "phone_number",
        ]

    first_name = forms.CharField(
        label='First Name',
        widget=forms.TextInput(attrs={
            'placeholder': 'Type first name',
            'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500'  # noqa
        }),
        error_messages={
            'required': 'This field must not be empty'
        },
        required=True,
    )

    last_name = forms.CharField(
        label='Last Name',
        widget=forms.TextInput(attrs={
            'placeholder': 'Type last name',
            'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500'  # noqa
        }),
        error_messages={
            'required': 'This field must not be empty'
        },
        required=True,
    )

    email = forms.CharField(
        label='Email',
        widget=forms.EmailInput(attrs={
            'placeholder': 'Type email',
            'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500'  # noqa
        }),
        error_messages={
            'required': 'This field must not be empty'
        },
        required=True,
    )

    phone_number = forms.CharField(
        label='Phone Number',
        widget=forms.TextInput(attrs={
            'placeholder': 'Type phone number',
            'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500'  # noqa
        }),
        error_messages={
            'required': 'This field must not be empty'
        },
        required=True,
    )

leads/forms/category_create_form.py
from django import forms
from leads.models import Category


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            "name",
            "description",
        ]

    name = forms.CharField(
        label='Name',
        widget=forms.TextInput(attrs={
            'placeholder': 'Type category name',
            'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500'  # noqa
        }),
        error_messages={
            'required': 'This field must not be empty'
        },
        required=True,
    )

    description = forms.CharField(
        label='Description',
        widget=forms.Textarea(attrs={
            'placeholder': 'Write category description here',
            'rows': '2',
            'class': 'block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500'  # noqa
        }),
        error_messages={
            'required': 'This field must not be empty'
        },
        required=True,
    )

leads/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.http.response import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from leads.models import Category, Lead, Agent
from .forms import CategoryForm, LeadForm, AgentForm
from utils.pagination import make_pagination_range
import pandas


class LeadView(LoginRequiredMixin, generic.View):
    login_url = "accounts:login"
    form = LeadForm
    template_name = 'dashboard/pages/leads.html'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def setup(self, *args, **kwargs):
        return super().setup(*args, **kwargs)

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request):
        form = self.form()
        leads = Lead.objects.all().order_by('-id')
        current_page = int(request.GET.get('page', 1))
        paginator = Paginator(leads, per_page=10)
        page_obj = paginator.get_page(current_page)
        pagination_range = make_pagination_range(
            page_range=paginator.page_range,
            qty_pages=4,
            current_page=current_page,
        )
        context = {
            'form': form,
            'leads': page_obj,
            'pagination_range': pagination_range
        }

        return render(request, self.template_name, context=context)

    def post(self, request):
        form = self.form(request.POST)
        url = reverse_lazy('dashboard:leads')

        if form.is_valid():
            form.save()
            messages.success(request, 'Lead created successfully')
            return redirect(url)
        else:
            messages.error(request, 'Lead not created successfully')
            return redirect(url)


class LeadSearchView(LeadView):
    login_url = "accounts:login"
    form = LeadForm
    template_name = 'dashboard/pages/leads.html'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def setup(self, *args, **kwargs):
        return super().setup(*args, **kwargs)

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request):
        form = self.form()
        search_term = self.request.GET.get('q', '').strip()
        leads = Lead.objects.filter(
            Q(
                Q(first_name__icontains=search_term) |
                Q(last_name__icontains=search_term) |
                Q(email__icontains=search_term) |
                Q(age__icontains=search_term) |
                Q(category__name__icontains=search_term) |
                Q(agent__first_name__icontains=search_term),
            )
        ).order_by('-id')

        current_page = int(request.GET.get('page', 1))
        paginator = Paginator(leads, per_page=10)
        page_obj = paginator.get_page(current_page)

        pagination_range = make_pagination_range(
            page_range=paginator.page_range,
            qty_pages=4,
            current_page=current_page,
        )

        if not search_term:
            raise Http404()

        context = {
            'form': form,
            'leads': page_obj,
            'pagination_range': pagination_range,
            'search_term': search_term,
            'additional_url_query': f'&q={search_term}',
        }

        return render(request, self.template_name, context=context)


class LeadUpdateView(LoginRequiredMixin, generic.UpdateView):  # noqa
    login_url = "accounts:login"
    model = Lead
    form = LeadForm
    fields = [
        "first_name",
        "last_name",
        "email",
        "age",
        "category",
        "agent",
    ]
    template_name = 'dashboard/partials/lead/lead_table_update_modal.html'  # noqa

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def setup(self, *args, **kwargs):
        return super().setup(*args, **kwargs)

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def post(self, request, pk):
        lead = Lead.objects.get(id=pk)
        form = LeadForm(instance=lead)
        form = self.form(request.POST, instance=lead)
        url = reverse_lazy('dashboard:leads')

        if form.is_valid():
            form.save()
            messages.success(request, 'Lead updated successfully')
            return redirect(url)

        messages.error(request, 'Lead not updated successfully')
        return redirect(url)


class LeadDeleteView(LoginRequiredMixin, SuccessMessageMixin, generic.DeleteView):  # noqa
    login_url = "accounts:login"
    template_name = 'dashboard/partials/lead/lead_table_delete_modal.html'  # noqa
    success_message = 'Lead deleted successfully'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def setup(self, *args, **kwargs):
        return super().setup(*args, **kwargs)

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_object(self):
        _id = int(self.kwargs.get('pk'))
        lead = get_object_or_404(Lead, pk=_id)
        return lead

    def get_success_url(self):
        return reverse_lazy('dashboard:leads')


class LeadExportView(LoginRequiredMixin, SuccessMessageMixin, generic.DeleteView):  # noqa
    login_url = "accounts:login"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def setup(self, *args, **kwargs):
        return super().setup(*args, **kwargs)

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request):
        leads = Lead.objects.all().order_by('-id')
        data = []

        for lead in leads:
            data.append({
                "first_name": lead.first_name,
                "last_name": lead.last_name,
                "email": lead.email,
                "age": lead.age,
                "category": lead.category,
                "agent": lead.agent
            })

        messages.success(request, 'Lead export successfully')
        pandas.DataFrame(data).to_excel('leads.xlsx')

        return redirect('dashboard:leads')


class CategoryView(LoginRequiredMixin, generic.View):
    login_url = "accounts:login"
    form = CategoryForm
    template_name = 'dashboard/pages/leads_category.html'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def setup(self, *args, **kwargs):
        return super().setup(*args, **kwargs)

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request):
        form = self.form()
        categories = Category.objects.all().order_by('-id')
        current_page = int(request.GET.get('page', 1))
        paginator = Paginator(categories, per_page=10)
        page_obj = paginator.get_page(current_page)
        pagination_range = make_pagination_range(
            page_range=paginator.page_range,
            qty_pages=4,
            current_page=current_page,
        )
        context = {
            'form': form,
            'categories': page_obj,
            'pagination_range': pagination_range
        }

        return render(request, self.template_name, context=context)

    def post(self, request):
        form = self.form(request.POST)
        url = reverse_lazy('dashboard:leads_category')

        if form.is_valid():
            form.save()
            messages.success(request, 'Category created successfully')
            return redirect(url)
        else:
            messages.error(request, 'Category not created successfully')
            return redirect(url)


class CategorySearchView(CategoryView):
    login_url = "accounts:login"
    form = CategoryForm
    template_name = 'dashboard/pages/leads_category.html'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def setup(self, *args, **kwargs):
        return super().setup(*args, **kwargs)

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request):
        form = self.form()
        search_term = self.request.GET.get('q', '').strip()
        categories = Category.objects.filter(
            Q(
                Q(name__icontains=search_term) |
                Q(description__icontains=search_term),
            )
        ).order_by('-id')

        current_page = int(request.GET.get('page', 1))
        paginator = Paginator(categories, per_page=10)
        page_obj = paginator.get_page(current_page)

        pagination_range = make_pagination_range(
            page_range=paginator.page_range,
            qty_pages=4,
            current_page=current_page,
        )

        if not search_term:
            raise Http404()

        context = {
            'form': form,
            'categories': page_obj,
            'pagination_range': pagination_range,
            'search_term': search_term,
            'additional_url_query': f'&q={search_term}',
        }

        return render(request, self.template_name, context=context)


class CategoryUpdateView(LoginRequiredMixin, generic.UpdateView):  # noqa
    login_url = "accounts:login"
    model = Category
    form = CategoryForm
    fields = ["name", "description"]
    template_name = 'dashboard/partials/category/category_table_update_modal.html'  # noqa

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def setup(self, *args, **kwargs):
        return super().setup(*args, **kwargs)

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def post(self, request, pk):
        category = Category.objects.get(id=pk)

templates/dashboard/partials/lead/lead_table.html
<section class="bg-gray-50 dark:bg-gray-900 p-3 sm:p-5">
    <div class="mx-auto max-w-screen-xl px-4 lg:px-12">
        <div class="bg-white dark:bg-gray-800 relative shadow-md sm:rounded-lg overflow-hidden">
            {% include "dashboard/partials/lead/lead_table_head.html" %}
            {% if leads %}
                {% include "dashboard/partials/lead/lead_table_content.html" %}
                {% include "dashboard/partials/lead/lead_table_nav.html" %}
            {% else %}
                {% include "dashboard/partials/lead/lead_table_empty_state.html" %}
            {% endif %}
            {% include "dashboard/partials/lead/lead_table_create_modal.html" %}
            {% include "dashboard/partials/lead/lead_table_update_modal.html" %}
            {% include "dashboard/partials/lead/lead_table_delete_modal.html" %}
        </div>
    </div>
</section>

templates/dashboard/partials/lead/lead_table_content.html
<div class="overflow-x-auto">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-4 py-3">First Name</th>
                <th scope="col" class="px-4 py-3">Last Name</th>
                <th scope="col" class="px-4 py-3">Email</th>
                <th scope="col" class="px-4 py-3">Age</th>
                <th scope="col" class="px-4 py-3">Category</th>
                <th scope="col" class="px-4 py-3">Agent</th>
                <th scope="col" class="px-4 py-3">Created At</th>
                <th scope="col" class="px-4 py-3">Updated At</th>
                <th scope="col" class="px-4 py-3">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for lead in leads %}
                <tr class="border-b dark:border-gray-700">
                    <td class="px-4 py-3">{{ lead.first_name }}</td>
                    <td class="px-4 py-3">{{ lead.last_name }}</td>
                    <td class="px-4 py-3">{{ lead.email }}</td>
                    <td class="px-4 py-3">{{ lead.age }}</td>
                    <td class="px-4 py-3">{{ lead.category.name }}</td>
                    <td class="px-4 py-3">{{ lead.agent.first_name }}</td>
                    <td class="px-4 py-3">{{ lead.created_at|date:'Y-m-d' }}</td>
                    <td class="px-4 py-3">{{ lead.updated_at|date:'Y-m-d' }}</td>
                    <td class="px-4 py-3">
                        <a href="javascript:void(0)"
                           name="item_delete"
                           class="font-medium hover:underline"
                           data-url="{% url 'dashboard:leads_delete' pk=lead.id %}"
                           data-target="#itemDeleteModal"
                           data-modal-toggle="itemDeleteModal">Remove</a>
                        <a href="#"
                           name="item_update"
                           class="font-medium hover:underline"
                           data-url="{% url 'dashboard:leads_update' pk=lead.id %}"
                           data-target="#itemUpdateModal"
                           data-modal-toggle="itemUpdateModal">Edit</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

templates/dashboard/partials/lead/lead_table_create_modal.html
<!-- Main modal -->
<div id="leadCreateModal"
     tabindex="-1"
     aria-hidden="true"
     class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-modal md:h-full">
    <div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
        <!-- Modal content -->
        <div class="relative p-4 bg-white rounded-lg shadow dark:bg-gray-800 sm:p-5">
            <!-- Modal header -->
            <div class="flex justify-between items-center pb-4 mb-4 rounded-t border-b sm:mb-5 dark:border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Create Lead</h3>
                <button type="button"
                        class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white"
                        data-modal-toggle="leadCreateModal">
                    <svg aria-hidden="true"
                         class="w-5 h-5"
                         fill="currentColor"
                         viewBox="0 0 20 20"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd">
                        </path>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <form action="" method="POST">
                {% csrf_token %}
                <div class="grid gap-4 mb-4 sm:grid-cols-2">
                    {% for field in form %}
                        <div class="sm:col-span-2">
                            <label for="{{ field.id_for_label }}"
                                   class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                                {{ field.label }}
                            </label>
                            {{ field }}
                            {% if field.errors %}
                                <span class="flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1">{{ field.errors }}</span>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <button type="submit"
                        class="text-white inline-flex items-center bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                    <svg class="mr-1 -ml-1 w-6 h-6"
                         fill="currentColor"
                         viewBox="0 0 20 20"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd">
                        </path>
                    </svg>
                    Create lead
                </button>
            </form>
        </div>
    </div>
</div>

templates/dashboard/partials/lead/lead_table_empty_state.html
<section class="bg-white dark:bg-gray-800">
    <div class="py-8 px-4 mx-auto max-w-screen-md text-center lg:py-16 lg:px-12">
        <i class="fa-solid fa-magnifying-glass fa-3x mx-auto mb-5 text-gray-400"></i>
        <h1 class="mb-4 text-4xl font-bold tracking-tight leading-none text-gray-900 lg:mb-6 md:text-5xl xl:text-4xl dark:text-white">
            No results found.
        </h1>
        <p class="font-light text-gray-500 md:text-lg xl:text-xl dark:text-gray-400">
            Try search again for a lead or back for
            <a href="{% url 'dashboard:leads' %}"
               class="font-medium text-blue-600 dark:text-blue-500 hover:underline">lead page</a>.
        </p>
    </div>
</section>

templates/dashboard/partials/lead/lead_table_head.html
<div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 p-4">
    <div class="w-full md:w-1/2">
        <form action="{% url 'dashboard:leads_search' %}" class="flex items-center">
            <label for="simple-search" class="sr-only">Search</label>
            <div class="relative w-full">
                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                    <svg aria-hidden="true"
                         class="w-5 h-5 text-gray-500 dark:text-gray-400"
                         fill="currentColor"
                         viewbox="0 0 20 20"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                    </svg>
                </div>
                <input type="text"
                       id="simple-search"
                       name="q"
                       value="{{ search_term }}"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full pl-10 p-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                       placeholder="Search for a lead"
                       required="">
            </div>
        </form>
    </div>
    <div class="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">
        <button type="button"
                data-modal-toggle="leadCreateModal"
                name="create_modal"
                class="flex items-center justify-center text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800">
            <svg class="h-3.5 w-3.5 mr-2"
                 fill="currentColor"
                 viewbox="0 0 20 20"
                 xmlns="http://www.w3.org/2000/svg"
                 aria-hidden="true">
                <path clip-rule="evenodd" fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" />
            </svg>
            Create Lead
        </button>
        <div class="flex items-center space-x-3 w-full md:w-auto">
            <button id="actionsDropdownButton"
                    data-dropdown-toggle="actionsDropdown"
                    class="w-full md:w-auto flex items-center justify-center py-2 px-4 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-primary-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700"
                    type="button">
                <svg class="-ml-1 mr-1.5 w-5 h-5"
                     fill="currentColor"
                     viewbox="0 0 20 20"
                     xmlns="http://www.w3.org/2000/svg"
                     aria-hidden="true">
                    <path clip-rule="evenodd" fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" />
                </svg>
                Actions
            </button>
            <div id="actionsDropdown"
                 class="hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600">
                <ul class="py-1 text-sm text-gray-700 dark:text-gray-200"
                    aria-labelledby="actionsDropdownButton">
                    <li>
                        <a href="{% url 'dashboard:leads_export' %}"
                           class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Export</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>