config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

dashboard/urls.py
from . import views
from leads import views as leads_views
from accounts import views as accounts_views
from django.urls import path

app_name = "dashboard"

urlpatterns = [
    path(
        '',
        views.DashboardView.as_view(),
        name='home'
    ),
    path(
        'profile/',
        accounts_views.UserProfileView.as_view(),
        name='profile'
    ),
    path(
        'leads/',
        leads_views.LeadView.as_view(),
        name='leads'
    ),
    path(
        'leads/search/',
        leads_views.LeadSearchView.as_view(),
        name='leads_search'
    ),
    path(
        'leads/export/',
        leads_views.LeadExportView.as_view(),
        name='leads_export'
    ),
    path(
        'leads/<int:pk>/update/',
        leads_views.LeadUpdateView.as_view(),
        name='leads_update'
    ),
    path(
        'leads/<int:pk>/delete/',
        leads_views.LeadDeleteView.as_view(),
        name='leads_delete'
    ),
    path(
        'leads/category/',
        leads_views.CategoryView.as_view(),
        name='leads_category'
    ),
    path(
        'leads/category/search/',
        leads_views.CategorySearchView.as_view(),
        name='leads_category_search'
    ),
    path(
        'leads/category/export/',
        leads_views.CategoryExportView.as_view(),
        name='leads_category_export'
    ),
    path(
        'leads/category/<int:pk>/update/',
        leads_views.CategoryUpdateView.as_view(),
        name='leads_category_update'
    ),
    path(
        'leads/category/<int:pk>/delete/',
        leads_views.CategoryDeleteView.as_view(),
        name='leads_category_delete'
    ),
    path(
        'leads/agent/',
        leads_views.AgentView.as_view(),
        name='leads_agent'
    ),
    path(
        'leads/agent/export/',
        leads_views.AgentExportView.as_view(),
        name='leads_agent_export'
    ),
    path(
        'leads/agent/search/',
        leads_views.AgentSearchView.as_view(),
        name='leads_agent_search'
    ),
    path(
        'leads/agent/<int:pk>/update/',
        leads_views.AgentUpdateView.as_view(),
        name='leads_agent_update'
    ),
    path(
        'leads/agent/<int:pk>/delete/',
        leads_views.AgentDeleteView.as_view(),
        name='leads_agent_delete'
    ),
]

users/urls.py
from . import views
from django.urls import path


app_name = "users"

urlpatterns = [
    path(
        '',
        views.LoginView.as_view(),
        name='login'
    ),
    path(
        'users/register/',
        views.RegisterView.as_view(),
        name='register'
    ),
    path(
        'users/logout/',
        views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        'users/password-reset/',
        views.PasswordResetCustomView.as_view(),
        name="password_reset"
    ),
    path(
        'users/password-reset-confirm/<uidb64>/<token>',
        views.PasswordResetConfirmCustomView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name="password_reset_confirm"
    ),
]

templates/dashboard/partials/agent/agent_table.html
<section class="bg-gray-50 dark:bg-gray-900 p-3 sm:p-5">
    <div class="mx-auto max-w-screen-xl px-4 lg:px-12">
        <div class="bg-white dark:bg-gray-800 relative shadow-md sm:rounded-lg overflow-hidden">
            {% include "dashboard/partials/agent/agent_table_head.html" %}
            {% if agents %}
                {% include "dashboard/partials/agent/agent_table_content.html" %}
                {% include "dashboard/partials/agent/agent_table_nav.html" %}
            {% else %}
                {% include "dashboard/partials/agent/agent_table_empty_state.html" %}
            {% endif %}
            {% include "dashboard/partials/agent/agent_table_create_modal.html" %}
            {% include "dashboard/partials/agent/agent_table_update_modal.html" %}
            {% include "dashboard/partials/agent/agent_table_delete_modal.html" %}
        </div>
    </div>
</section>

templates/dashboard/partials/agent/agent_table_content.html
<div class="overflow-x-auto">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-4 py-3">First Name</th>
                <th scope="col" class="px-4 py-3">Last Name</th>
                <th scope="col" class="px-4 py-3">Email</th>
                <th scope="col" class="px-4 py-3">Phone Number</th>
                <th scope="col" class="px-4 py-3">Created At</th>
                <th scope="col" class="px-4 py-3">Updated At</th>
                <th scope="col" class="px-4 py-3">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for agent in agents %}
                <tr class="border-b dark:border-gray-700">
                    <td class="px-4 py-3">{{ agent.first_name }}</td>
                    <td class="px-4 py-3">{{ agent.last_name }}</td>
                    <td class="px-4 py-3">{{ agent.email }}</td>
                    <td class="px-4 py-3">{{ agent.phone_number }}</td>
                    <td class="px-4 py-3">{{ agent.created_at|date:'Y-m-d' }}</td>
                    <td class="px-4 py-3">{{ agent.updated_at|date:'Y-m-d' }}</td>
                    <td class="px-4 py-3">
                        <a href="javascript:void(0)"
                        name="item_delete"
                        class="font-medium hover:underline"
                        data-url="{% url 'dashboard:leads_agent_delete' pk=agent.id %}"
                        data-target="#itemDeleteModal"
                        data-modal-toggle="itemDeleteModal">Remove</a>
                        <a href="#"
                        name="item_update"
                        class="font-medium hover:underline"
                        data-url="{% url 'dashboard:leads_agent_update' pk=agent.id %}"
                        data-target="#itemUpdateModal"
                        data-modal-toggle="itemUpdateModal">Edit</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

templates/dashboard/partials/agent/agent_table_create_modal.html
<!-- Main modal -->
<div id="agentCreateModal"
     tabindex="-1"
     aria-hidden="true"
     class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-modal md:h-full">
    <div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
        <!-- Modal content -->
        <div class="relative p-4 bg-white rounded-lg shadow dark:bg-gray-800 sm:p-5">
            <!-- Modal header -->
            <div class="flex justify-between items-center pb-4 mb-4 rounded-t border-b sm:mb-5 dark:border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Create agent</h3>
                <button type="button"
                        class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white"
                        data-modal-toggle="agentCreateModal">
                    <svg aria-hidden="true"
                         class="w-5 h-5"
                         fill="currentColor"
                         viewBox="0 0 20 20"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd">
                        </path>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <form action="" method="POST">
                {% csrf_token %}
                <div class="grid gap-4 mb-4 sm:grid-cols-2">
                    {% for field in form %}
                        <div class="sm:col-span-2">
                            <label for="{{ field.id_for_label }}"
                                   class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                                {{ field.label }}
                            </label>
                            {{ field }}
                            {% if field.errors %}
                                <span class="flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1">{{ field.errors }}</span>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <button type="submit"
                        class="text-white inline-flex items-center bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                    <svg class="mr-1 -ml-1 w-6 h-6"
                         fill="currentColor"
                         viewBox="0 0 20 20"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd">
                        </path>
                    </svg>
                    Create agent
                </button>
            </form>
        </div>
    </div>
</div>

templates/dashboard/partials/agent/agent_table_delete_modal.html
{% load static %}
<div id="itemDeleteModal"
     tabindex="-1"
     aria-hidden="true"
     class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-modal md:h-full">
    <div class="relative p-4 w-full max-w-md h-full md:h-auto">
        <!-- Modal content -->
        <div class="relative p-4 text-center bg-white rounded-lg shadow dark:bg-gray-800 sm:p-5">
            <button type="button"
                    class="text-gray-400 absolute top-2.5 right-2.5 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white"
                    data-modal-toggle="itemDeleteModal">
                <svg aria-hidden="true"
                     class="w-5 h-5"
                     fill="currentColor"
                     viewBox="0 0 20 20"
                     xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd">
                    </path>
                </svg>
                <span class="sr-only">Close modal</span>
            </button>
            <svg class="text-gray-400 dark:text-gray-500 w-11 h-11 mb-3.5 mx-auto"
                 aria-hidden="true"
                 fill="currentColor"
                 viewBox="0 0 20 20"
                 xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd">
                </path>
            </svg>
            <p class="mb-4 text-gray-500 dark:text-gray-300">Are you sure you want to delete this item?</p>
            <div class="flex justify-center items-center space-x-4">
                <button data-modal-toggle="itemDeleteModal"
                        type="button"
                        class="py-2 px-3 text-sm font-medium text-gray-500 bg-white rounded-lg border border-gray-200 hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-primary-300 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">
                    No, cancel
                </button>
                <form action="" method="POST" id="form_confirm_delete_modal">
                    {% csrf_token %}
                    <button type="button"
                            id="confirmDeleteButtonModal"
                            class="py-2 px-3 text-sm font-medium text-center text-white bg-red-600 rounded-lg hover:bg-red-700 focus:ring-4 focus:outline-none focus:ring-red-300 dark:bg-red-500 dark:hover:bg-red-600 dark:focus:ring-red-900">
                        Yes, I'm sure
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static 'js/modal_delete.js' %}"></script>

templates/dashboard/partials/agent/agent_table_empty_state.html
<section class="bg-white dark:bg-gray-800">
    <div class="py-8 px-4 mx-auto max-w-screen-md text-center lg:py-16 lg:px-12">
        <i class="fa-solid fa-magnifying-glass fa-3x mx-auto mb-5 text-gray-400"></i>
        <h1 class="mb-4 text-4xl font-bold tracking-tight leading-none text-gray-900 lg:mb-6 md:text-5xl xl:text-4xl dark:text-white">
            No results found.
        </h1>
        <p class="font-light text-gray-500 md:text-lg xl:text-xl dark:text-gray-400">
            Try search again for a agent or back for
            <a href="{% url 'dashboard:leads_agent' %}"
               class="font-medium text-blue-600 dark:text-blue-500 hover:underline">agent page</a>.
        </p>
    </div>
</section>

templates/dashboard/partials/agent/agent_table_head.html
<div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 p-4">
    <div class="w-full md:w-1/2">
        <form action="{% url 'dashboard:leads_agent_search' %}"
              class="flex items-center">
            <label for="simple-search" class="sr-only">Search</label>
            <div class="relative w-full">
                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                    <svg aria-hidden="true"
                         class="w-5 h-5 text-gray-500 dark:text-gray-400"
                         fill="currentColor"
                         viewbox="0 0 20 20"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                    </svg>
                </div>
                <input type="text"
                       id="simple-search"
                       name="q"
                       value="{{ search_term }}"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full pl-10 p-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                       placeholder="Search for a agent"
                       required="">
            </div>
        </form>
    </div>
    <div class="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">
        <button type="button"
                data-modal-toggle="agentCreateModal"
                class="flex items-center justify-center text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800">
            <svg class="h-3.5 w-3.5 mr-2"
                 fill="currentColor"
                 viewbox="0 0 20 20"
                 xmlns="http://www.w3.org/2000/svg"
                 aria-hidden="true">
                <path clip-rule="evenodd" fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" />
            </svg>
            Create Agent
        </button>
        <div class="flex items-center space-x-3 w-full md:w-auto">
            <button id="actionsDropdownButton"
                    data-dropdown-toggle="actionsDropdown"
                    class="w-full md:w-auto flex items-center justify-center py-2 px-4 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-primary-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700"
                    type="button">
                <svg class="-ml-1 mr-1.5 w-5 h-5"
                     fill="currentColor"
                     viewbox="0 0 20 20"
                     xmlns="http://www.w3.org/2000/svg"
                     aria-hidden="true">
                    <path clip-rule="evenodd" fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" />
                </svg>
                Actions
            </button>
            <div id="actionsDropdown"
                 class="hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600">
                <ul class="py-1 text-sm text-gray-700 dark:text-gray-200"
                    aria-labelledby="actionsDropdownButton">
                    <li>
                        <a href="{% url 'dashboard:leads_agent_export' %}"
                           class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Export</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

templates/dashboard/partials/agent/agent_table_nav.html
<nav class="flex flex-col md:flex-row justify-between items-start md:items-center space-y-3 md:space-y-0 p-4"
     aria-label="Table navigation">
    <span class="text-sm font-normal text-gray-500 dark:text-gray-400">
        Showing
        <span class="font-semibold text-gray-900 dark:text-white">{{ agents.number }}</span>
        of
        <span class="font-semibold text-gray-900 dark:text-white">{{ agents.paginator.num_pages }}</span>
    </span>
    <ul class="inline-flex items-stretch -space-x-px">
        {% if pagination_range.first_page_out_of_range %}
            <li>
                <a class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
                   href="?page=1{{ additional_url_query }}">1</a>
            </li>
            <li>
                <span class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">...</span>
            </li>
        {% endif %}
        {% for page in pagination_range.pagination %}
            {% if pagination_range.current_page == page %}
                <li>
                    <a class="flex items-center justify-center text-sm z-10 py-2 px-3 leading-tight text-primary-600 bg-primary-50 border border-primary-300 hover:bg-primary-100 hover:text-primary-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white"
                       href="?page={{ page }}{{ additional_url_query }}">{{ page }}</a>
                </li>
            {% else %}
                <li>
                    <a class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
                       href="?page={{ page }}{{ additional_url_query }}">{{ page }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if pagination_range.last_page_out_of_range %}
            <li>
                <span class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">...</span>
            </li>
            <li>
                <a class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
                   href="?page={{ pagination_range.total_pages }}{{ additional_url_query }}">{{ pagination_range.total_pages }}</a>
            </li>
        {% endif %}
    </ul>
</nav>

templates/dashboard/partials/agent/agent_table_update_modal.html
<!-- Main modal -->
{% load static %}
<div id="itemUpdateModal"
     tabindex="-1"
     aria-hidden="true"
     class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-modal md:h-full">
    <div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
        <!-- Modal content -->
        <div class="relative p-4 bg-white rounded-lg shadow dark:bg-gray-800 sm:p-5">
            <!-- Modal header -->
            <div class="flex justify-between items-center pb-4 mb-4 rounded-t border-b sm:mb-5 dark:border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Update Agent</h3>
                <button type="button"
                        class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white"
                        data-modal-toggle="itemUpdateModal">
                    <svg aria-hidden="true"
                         class="w-5 h-5"
                         fill="currentColor"
                         viewBox="0 0 20 20"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd">
                        </path>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <form action="" method="POST" id="form_confirm_update_modal">
                {% csrf_token %}
                <div class="grid gap-4 mb-4 sm:grid-cols-2">
                    {% for field in form %}
                        <div class="sm:col-span-2">
                            <label for="{{ field.id_for_label }}"
                                   class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                                {{ field.label }}
                            </label>
                            {{ field }}
                            {% if field.errors %}
                                <span class="flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1">{{ field.errors }}</span>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <button type="button"
                        id="confirmUpdateButtonModal"
                        class="text-white inline-flex items-center bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                    <svg class="mr-1 -ml-1 w-6 h-6"
                         fill="currentColor"
                         viewBox="0 0 20 20"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd">
                        </path>
                    </svg>
                    Update agent
                </button>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static 'js/modal_update.js' %}"></script>